#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "json.h"
#include "standings.h"
typedef struct {char *p;size_t len,cap;} Buf; static int grow(Buf*b,size_t extra){if(b->len+extra+1<=b->cap)return 1;size_t c=b->cap?b->cap*2:512;while(c<b->len+extra+1)c*=2;char*p=realloc(b->p,c);if(!p)return 0;b->p=p;b->cap=c;return 1;} static void add(Buf*b,const char*s){size_t z=strlen(s);if(grow(b,z)){memcpy(b->p+b->len,s,z);b->len+=z;b->p[b->len]=0;}}static void num(Buf*b,int x){char t[32];snprintf(t,sizeof t,"%d",x);add(b,t);}static void esc(Buf*b,const char*s){add(b,"\"");for(;s&&*s;s++){if(*s=='\"'||*s=='\\'){char q[3]={'\\',*s,0};add(b,q);}else if((unsigned char)*s>=32){char q[2]={*s,0};add(b,q);}}add(b,"\"");}static char*done(Buf*b){if(!b->p)return NULL;return b->p;}
int json_get_string(const char *body,const char *key,char*out,size_t size){char find[128];const char*p;size_t i=0;if(!body||!out||!size)return 0;snprintf(find,sizeof find,"\"%s\"",key);p=strstr(body,find);if(!p||(p=strchr(p+strlen(find),':'))==NULL)return 0;p++;while(isspace((unsigned char)*p))p++;if(*p!='\"')return 0;p++;while(*p&&*p!='\"'&&i+1<size){if(*p=='\\'&&p[1])p++;out[i++]=*p++;}out[i]=0;return *p=='\"';}
int json_get_int(const char *body,const char *key,int*out){char find[128];const char*p; if(!body||!out)return 0;snprintf(find,sizeof find,"\"%s\"",key);p=strstr(body,find);if(!p||(p=strchr(p+strlen(find),':'))==NULL)return 0;return sscanf(p+1,"%d",out)==1;}
char *json_message(int ok,const char*m){Buf b={0};add(&b,"{\"success\":");add(&b,ok?"true":"false");add(&b,",\"message\":");esc(&b,m?m:"");add(&b,"}");return done(&b);}
static void status(Buf*b,TournamentStatus s){add(b,s==TOURNAMENT_DRAFT?"Draft":s==TOURNAMENT_ACTIVE?"Active":"Completed");}static void mstatus(Buf*b,MatchStatus s){add(b,s==MATCH_UPCOMING?"Upcoming":s==MATCH_COMPLETED?"Completed":"BYE");}
char *json_tournaments(const TournamentStore *store){Buf b={0};TournamentNode*n;add(&b,"{\"success\":true,\"data\":[");for(n=store->head;n;n=n->next){Tournament*t=&n->tournament;if(n!=store->head)add(&b,",");add(&b,"{\"id\":");num(&b,t->id);add(&b,",\"name\":");esc(&b,t->name);add(&b,",\"description\":");esc(&b,t->description);add(&b,",\"status\":");esc(&b,t->status==0?"Draft":t->status==1?"Active":"Completed");add(&b,",\"teams\":");num(&b,(int)t->team_count);add(&b,",\"matches\":");num(&b,(int)t->match_count);add(&b,"}");}add(&b,"]}");return done(&b);}
char *json_tournament(const Tournament*t){Buf b={0};add(&b,"{\"success\":true,\"data\":{\"id\":");num(&b,t->id);add(&b,",\"name\":");esc(&b,t->name);add(&b,",\"description\":");esc(&b,t->description);add(&b,",\"status\":");add(&b,"\"");status(&b,t->status);add(&b,"\",\"teams\":");num(&b,(int)t->team_count);add(&b,",\"matches\":");num(&b,(int)t->match_count);add(&b,",\"rounds\":");num(&b,t->rounds);add(&b,"}}");return done(&b);}
char *json_teams(const Tournament*t){Buf b={0};size_t i;add(&b,"{\"success\":true,\"data\":[");for(i=0;i<t->team_count;i++){Team*x=&t->teams[i];if(i)add(&b,",");add(&b,"{\"id\":");num(&b,x->id);add(&b,",\"name\":");esc(&b,x->name);add(&b,",\"city\":");esc(&b,x->city);add(&b,"}");}add(&b,"]}");return done(&b);}
char *json_matches(const Tournament*t){Buf b={0};size_t i;add(&b,"{\"success\":true,\"data\":[");for(i=0;i<t->match_count;i++){Match*m=&t->matches[i];Team*h=NULL,*a=NULL;size_t j;for(j=0;j<t->team_count;j++){if(t->teams[j].id==m->home_id)h=&t->teams[j];if(t->teams[j].id==m->away_id)a=&t->teams[j];}if(i)add(&b,",");add(&b,"{\"id\":");num(&b,m->id);add(&b,",\"round\":");num(&b,m->round);add(&b,",\"home\":");esc(&b,h?h->name:"BYE");add(&b,",\"away\":");esc(&b,a?a->name:"BYE");add(&b,",\"homeScore\":");num(&b,m->home_score);add(&b,",\"awayScore\":");num(&b,m->away_score);add(&b,",\"status\":\"");mstatus(&b,m->status);add(&b,"\"}");}add(&b,"]}");return done(&b);}
char *json_standings(const Tournament*t){Buf b={0};size_t i,n;Standing*s=standings_calculate(t,&n);add(&b,"{\"success\":true,\"data\":[");for(i=0;s&&i<n;i++){if(i)add(&b,",");add(&b,"{\"position\":");num(&b,(int)i+1);add(&b,",\"team\":");esc(&b,s[i].name);add(&b,",\"played\":");num(&b,s[i].played);add(&b,",\"wins\":");num(&b,s[i].wins);add(&b,",\"draws\":");num(&b,s[i].draws);add(&b,",\"losses\":");num(&b,s[i].losses);add(&b,",\"gf\":");num(&b,s[i].gf);add(&b,",\"ga\":");num(&b,s[i].ga);add(&b,",\"gd\":");num(&b,s[i].gd);add(&b,",\"points\":");num(&b,s[i].points);add(&b,"}");}free(s);add(&b,"]}");return done(&b);}
