#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "storage.h"
#include "tournament.h"
#define MAGIC 0x52525453u
static void fail(char *e,size_t n,const char *s){if(e&&n)snprintf(e,n,"%s",s);} static int writeall(const void*p,size_t z,FILE*f){return fwrite(p,z,1,f)==1;} static int readall(void*p,size_t z,FILE*f){return fread(p,z,1,f)==1;}
int storage_save(const TournamentStore *s,const char *path,char *e,size_t n){FILE*f=fopen(path,"wb");TournamentNode*x;unsigned magic=MAGIC,count=0; if(!f){fail(e,n,"Could not open storage file");return 0;}for(x=s->head;x;x=x->next)count++;if(!writeall(&magic,sizeof magic,f)||!writeall(&s->next_tournament_id,sizeof s->next_tournament_id,f)||!writeall(&count,sizeof count,f)){fclose(f);fail(e,n,"Write error");return 0;}for(x=s->head;x;x=x->next){Tournament*t=&x->tournament;if(!writeall(t,sizeof *t,f)||!writeall(t->teams,t->team_count*sizeof *t->teams,f)||!writeall(t->matches,t->match_count*sizeof *t->matches,f)){fclose(f);fail(e,n,"Write error");return 0;}}fclose(f);return 1;}
int storage_load(TournamentStore *s,const char *path,char *e,size_t n){FILE*f=fopen(path,"rb");unsigned magic,count,i;int next_id;if(!f){fail(e,n,"No saved data file found");return 0;}if(!readall(&magic,sizeof magic,f)||magic!=MAGIC||!readall(&next_id,sizeof next_id,f)||!readall(&count,sizeof count,f)){fclose(f);fail(e,n,"Invalid storage file");return 0;}store_free(s);s->next_tournament_id=next_id;for(i=0;i<count;i++){Tournament temp;TournamentNode*node;if(!readall(&temp,sizeof temp,f)||temp.team_count>10000||temp.match_count>100000){fclose(f);store_free(s);fail(e,n,"Corrupt storage data");return 0;}node=calloc(1,sizeof *node);if(!node){fclose(f);store_free(s);fail(e,n,"Out of memory");return 0;}node->tournament=temp;node->tournament.teams=malloc(temp.team_count*sizeof *temp.teams);node->tournament.matches=malloc(temp.match_count*sizeof *temp.matches);if((temp.team_count&&!node->tournament.teams)||(temp.match_count&&!node->tournament.matches)||!readall(node->tournament.teams,temp.team_count*sizeof *temp.teams,f)||!readall(node->tournament.matches,temp.match_count*sizeof *temp.matches,f)){free(node->tournament.teams);free(node->tournament.matches);free(node);fclose(f);store_free(s);fail(e,n,"Corrupt storage data");return 0;}node->next=s->head;s->head=node;}fclose(f);return 1;}
